#!/bin/bash -eu

# Force this to the working directory
cd "$(dirname "$0")"

mkdir -p ../../assets/data

gzcat wikiticker-2015-09-12.gz \
  | jq -c '
    select("2015-09-12" < .timestamp and .timestamp < "2015-09-13") |
    {
      time: .timestamp,
      channel,
      cityName,
      comment,
      countryIsoCode,
      countryName,
      isAnonymous: (.countryName != null),
      isMinor,
      isNew,
      isRobot,
      isUnpatrolled,
      metroCode,
      namespace,
      page,
      regionIsoCode,
      regionName,
      user,
      delta,
      added: [.delta, 0] | max,
      deleted: [-.delta, 0] | max
    }' \
  > ../data/wikiticker-2015-09-12-large.json

perl -ne'print if $. % 10 == 0' ../data/wikiticker-2015-09-12-large.json \
  > ../data/wikiticker-2015-09-12-sampled.json

cat ../data/wikiticker-2015-09-12-large.json \
  | jq -c 'select(.isAnonymous)' \
  > ../data/wikiticker-2015-09-12-anonymous.json
