pull_request_rules:
  - name: automatic merge for GitHub actions
    conditions:
      - author=dependabot[bot]
      - check-success=all-checks # check all actions
      - label=github-actions # label assigned by dependabot
      - base=master
    actions:
      merge:
        method: rebase
  - name: automatic merge for Node dependencies
    conditions:
      - author=dependabot[bot]
      - check-success=required-checks # check required actions only
      - label=npm # label assigned by dependabot
      - base=master
    actions:
      merge:
        method: rebase
