files:
  include:
  - 'lib/style/*.s+(a|c)ss'
  - 'src/**/*.s+(a|c)ss'
rules:
  attribute-quotes: 2
  bem-depth: 2
  border-zero: 2
  brace-style: 2
  class-name-format:
  - 2
  - convention: hyphenatedbem
  - allow-leading-underscore: false
  clean-import-paths: 2
  declarations-before-nesting: 2
  empty-args: 2
  empty-line-between-blocks: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  force-attribute-nesting: 2
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format: 2
  hex-length: 2
  hex-notation: 2
  id-name-format:
  - 2
  - allow-leading-underscore: false
  indentation:
  - 2
  - size: 2
  leading-zero: 0
  max-file-line-count:
  - 2
  - length: 200
  max-line-length:
  - 2
  - length: 150
  mixin-name-format: 2
  mixins-before-declarations: 2
  nesting-depth:
  - 2
  - max-depth: 4
  no-color-keywords: 2
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 2
  no-disallowed-properties: 2
  no-duplicate-properties:
  - 2
  - exclude:
    - src
  no-empty-rulesets: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 0
  no-transition-all: 2
  no-url-protocols: 2
  no-vendor-prefixes:
  - 2
  - excluded-identifiers:
    - ms
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format: 2
  property-sort-order: 0
  property-units: 2
  pseudo-element: 2
  quotes: 2
  single-line-per-selector: 0
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property: 2
  variable-name-format: 2
  zero-unit: 2
