#!/bin/bash -eu

# Use a reporter that does not take a ton of height
node node_modules/.bin/istanbul cover node_modules/.bin/_mocha -- --reporter progress build/common/**/*.mocha.js build/client/**/*.mocha.js
