/*
 * Copyright 2017-2018 Allegro.pl
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class UrlHashConverterFixtures {
  static tableHashVersion2() {
    return "table/2/EQUQLgxg9AqgKgYWAGgN7APYAdgC5gCGAdgCYqZYCmATsWbutnoaedjXXozvp8hR1YMKzPgNpDuo1v3YT6U/BgBuNADYEcsqvK4j81SgDNyRAgFtKzMA" +
      "EtLwAL79KADyyGAzh5sYiepvhqNmAcauTKBGoArlbCHmAE1GDMAEwADACMAKwAtGkAnDkZKXBpabhlFWkAdGVpAFrklELA6dl5hRkAzKXllWW1ZY1OwGAAnlTMcACSALI" +
      "gAPoASgCCAHIA4iCOI67ulF4+fsIBmKrUGlrinCc8wIYm/Gb2+BAAFsRElGG7bp7evn8dyCIVoYX4EWisXQHkoYDgE1iwAAynAltNNk01JRLEQwB48ABtYDNYAAXRG40m" +
      "+GRIDgO1++0OgNuzCIGGS2kECn0Z3UmjYOhuinuxlMFiRNg8SwwACMOY5nH8DgDjiKQaFwpEYnpYfDEcwAEIAeWNABkQOssTjmviiWBqDEKfwqUjafSHJ7Gf8jkDmBBfA" +
      "kbEQCVzdKyDGKnhLmFgCABzKzelW+iPADVgrVQ5gAKRoOLGiuAAfMccMbIw1HMkR2SqZqr9+GrkDegu5jdFj2AzyRUVh1AQH2oBJGhkTbmYAD0VgASWsk5XMtW8lT8q5y" +
      "YW8h7il7FjDmXFgM3NeNgVvJpcdjM1iHa6HAPUI6nANYwWaGkBLZbrLbWw8E3BCRhBIkjwLpnCEIgojUNQHGdUYDRpOkGWQICF3rVMRW3aNd3eT5viLDxKzAFYIFsFkRS" +
      "I0C6x9CityjbsY3wEhvgSIsSBsQwyNTYAWI8CBmg4oh4yLIJzGCUjyOXU4xOCLMdVwLI0k9NB0No6S7mwxjdylGV5WSEYqJI7i6NOIymkXBs0y0ntmBYtQ2JGDiuKkuyD" +
      "gE0hgxEkZZOM1y018+TYiyFT0D2dSOxspi9wPW1j2Es8i1lKIIAAazhSTMN5KDzFlGhDRS9LOQfGwAC9YgyZT+CMzLTLucyaJTOrmCi3d7Mc/hnMoEzjl49zBK80S7Akn" +
      "qr2G4rIQUkKnDCyystOVqkVsewRmStKMtGtNlsoAr1uKkgolofzgAABTgDIAAlCOI2qNOYBq1Kau7Iy7WzmNYgh2M47rjr4jyhO8/hfNusbxImu88CgmDPTJZAHRiTqPp" +
      "QYl2s+/gAyiPFyAIEgWLIWHiTwogvnBbSDjjATyF0uUFVhvqHLRqG1GQJmWegtQgA===";
  }

  static tableHashVersion3() {
    return "3/N4IgbglgzgrghgGwgLzgFwgewHYgFwhpwBGCApiADSEQC2ZyOFBAomgMYD0AqgCoDCVEADMICNGQBOUfAG1QaAJ4AHZjXpDJZYfnUVqGegCU42AOZkZeeSChFJ" +
      "aXQCYADAEYArAFoXATi9uTrwuLnghYS4AdCEuAFpCZNgAJs7u3n4BAMzBoeEh0SHxAL4AukWUCipqdpIQ5prauuwAFqbYZAhCcOwYOLp1QmCIMJZyIIkgJdTYmI54wohQ" +
      "ZOWVqrrEmJjkpg06BNBGmBuO1EMII1ayaJIjUyAzc9cjK4RVujV1Zru6ynAWXT0sLgCOwcEQ6jJTsNRtYQAApKRkWiKSbTWb4BYIJYvJRrAgferULR7EAwJaSfitaQA3r" +
      "AkC0dAtQbQy4gAB6AEEACSo+7o+aLZYVV54+4wWjEKTfEGYWj0bBoAAyiTMaGaQgeGMFRNMFkuoDscAc+Ey1ESKTw2BgCAQ1A2MGSVhAsgAlCBSqVqFBlEg0PqRdVrp8h" +
      "Ek6IkoECmq1sO1Ol7MMa8KBibokh0iCGIFpAX0CGmoOxzcHyiAkLQIHMPC4cW98UHCSBQ/KI7mQAcjuj44nk408+m4Jns7TU5ZC8li9QyxX8B4a6KrRKpdQm+HIzK5Ykl" +
      "Sq1UIzJJTNajRWUXg3C4u3MeyS0+IB8us2Qc3T82PQ/US1PK3O1IZ9I2w9gLZ0r+u77laCBHkougAAq8G4AASQhQAml4gCmfa3oOj7Dn2BZFu+k50NOlrWggnr0mQcCwF" +
      "oVigNAACy1oYPgTxkF6nzkCOmHULQTEQGMN4ZtQoIOicIBwEkaYpGU1DKHU7RJAAIgBQGsi0bQdBqcD0N63R/u2xy8nJMZkEkADKKFcUJpZkBYyT4OBtogM0EBmM0SBuX" +
      "MjlFEAA=";
  }

  static tableHashVersion4() {
    return "4/N4IgbglgzgrghgGwgLzgFwgewHYgFwhpwBGCApiADSEQC2ZyOFBAomgMYD0AqgCoDCVEADMICNGQBOUfAG1QaAJ4AHZjXpDJZYfnUVqGegCU42AOZkZeeSChFJ" +
      "aXQCYADAEYArAFoXATi9uTrwuLnghYS4AdCEuAFpCZNgAJs7u3n4BAMzBoeEh0SHxAL4AukWUCipqdpIQ5prauuwAFqbYZAhCcOwYOLp1QmCIMJZyIIkgJdTYmI54wohQ" +
      "ZOWVqrrEmJjkpg06BNBGmBuO1EMII1ayaJIjUyAzc9cjK4RVujV1Zru6ynAWXT0sLgCOwcEQ6jJTsNRtYQAApKRkWiKSbTWb4BYIJYvJRrAgferULR7EAwJaSfitaQA3r" +
      "AkC0dAtQbQy4gAB6AEEACSo+7o+aLZYVV54+4wWjEKTfEGYWj0bBoAAyiTMaGaQgeGMFRNMFkuoDscAc+Ey1ESKTw2BgCAQ1A2MGSVhAsgAlCBSqVqFBlEg0PqRdVrp8h" +
      "Ek6IkoECmq1sO1Ol7MMa8KBibokh0iEJcdUpBBRtRQ1pAX0CGmoOxzcHqKpapgLSB3dQkLQIHMPC4cW98UHCSBQ/KI8WQAcjuj44nk40S+m4JnO7Yc3nexBC7TU5Zy8lK" +
      "yBq1g6w2QE2W/gPB3RVaJVL82HsAO6aC5YklSq1UIzJJTNajS2UXg3C4x3ME4kmm4gzgYc7krmkJLiukZTmWFY9juta6Puh6tqeaiGPoS79nBeivu+VoIF+Si6AACrwbg" +
      "ABJCFACaASAKZTqBs6ipBi4FmQRZ0qWG6hkhOYoQQaF0EelrWggnrzrUMI2MSiLYOWa6sdQwgJgyjFZmuCzWic4DQqh5QBro9BwLAWgNkBinKTKDr6epkiafgqxqGmuni" +
      "My5xqPu2kEGZFkUC8ClaEpahwEkaYpGpGnoC5JlTh5+lnCMRngaKAUwJZ0nKHU7RJAAItet6si0bQdBqcD0N63Q4cOxy8rlMZkEkADKDEqRmjZkBYyT4MRtogM0EBmM0S" +
      "CjXMA1FEAA=";
  }

  static lineChartVersion2() {
    return "line-chart/2/EQUQLgxg9AqgKgYWAGgN7APYAdgC5gCGAdgCYqZYCmATsWbutnpgG40A2BOyFNdejHPmqUAZuSIEAtpWZgAljOABfHpQAeWEQGdt8jEQEU5iygC" +
      "ViAc1k9sfUkabCxE6bPxSVPEgFdaCg2YABQBGABFybTBKIQBaEOVVYA0tSl19QwZjfAw2ak5uXloHLKdgEXEeSSV8CAALYiJKdi9kzR09QNKhYHZ5aNoWnhYCdh93dG1K" +
      "MDgATypmAGU4MwBJADkAcXJmyhkiMG08AG1kwyqMSJZyEhtgUWpyCCOAXSSwefdgRZA4FUTkMd0CkOhlHD0Kq4asB6o1mq1tBhqGAAIIQAKZQTMRHInbtNKdTHZcouKpu" +
      "Zi3dhgAitEjyETosH4W7aCCUUjyIiWVp9KT9NEY8HMXn9cgjMbuACsAAYAcD8ekuljnJVgNUvgolEkAEY+CAAa2mAqZyuAmsoACE9YawDc/ARBfggnAQgAJBFI1GMpXEn" +
      "G2tQKwlClVQjWmWn0yjezKEVnsulc/4vZBgajjbzNakoU6UrM8CAYHwHcgEEi3MjJ06wohNIZqtzaLAENnkeTaMwYbUYW3J4C5mloPumIhB2oNGvw4ajcZHLLS5hES48E" +
      "LY648ADMzAe5AALMxnuRJcx2f9kEQfOx2IOMAB3JqPfB9JqxWG4jNUmndZi5Dhcch2Yp6FNSEyWhc1WhBAkTWJPoBlGMVpwmYAogIXF8AAJmlEJJViaUAE54nQl1pVwaU" +
      "SLIgA6MjpQALR2EpgEw7DcIIkIiJCEJSPI6UqLIuj3k+Zg4FWABZEAAH0zBRLYQFPYAZAIbQ/C+Asi1tZQgA";
  }

  static lineChartVersion3() {
    return "3/N4IgbglgzgrghgGwgLzgFwgewHYgFwhLYCmAtAMYAWcATmiADQgYC2xyOx+IAomuQHoAqgBUAwoxAAzCAjTEaUfAG1QaAJ4AHLgVZcmNYlO57JegAoKsAEyV5V" +
      "IazBrosuAuYCMAEUlR5mviknkwa2twI6MT+IAC+ALqxDGpaOiD+NBDYAOaShsYEVHDYJAiScOQYONxZkmCIMNEqIMS4TNiYfmCS1vrSNJLkSvHtmPR4UohQxAlMUJpIaH" +
      "YOYWkZWblM1hBs2FBu3EUlxGVzmHT4oPncvXJwPRCGlQcEvVDkrds5cUxILBDjACsAAYkilwrodn1trt9tVIWxJNkXNgYJFMhpuOYRJ4ABJ+c7jK5GExQh5PKruEBwd6f" +
      "DY/Qg7AH4VEIBCzEBsGnOJp4UDQACyaIw+DQNEacw2CDStzQ9yYLGFEGasvlIHImBg2HoTDg1l61hAiSYmiyJGs3ihezcy3V1GOpxA2DgbHmFT60AASpgAEZjI0ms3Eaw" +
      "AZUJNxOcsk0uyn0ujitcKpR1K0aZ41ZCCY9QQjTsoGB3A6kk83Cg3SYAGZuFIBkwACyHJRMQHcVoM6hQAByaLKEymMyYlAg2UoSFHRJAmAA7iQBgQiGQihcmDI5ApluC0" +
      "qYDCSEX09J7irHN+k5RcCAAmYGeQGkYEATmCl5xwLwwLfH4AdB/gQAtSQ4yvG870fZ8cU8d9P2BH8PwAhIOS5WBDEOTVtTiWIgA===";
  }

  static lineChartVersion4() {
    return "4/N4IgbglgzgrghgGwgLzgFwgewHYgFwhLYCmAtAMYAWcATmiADQgYC2xyOx+IAomuQHoAqgBUAwoxAAzCAjTEaUfAG1QaAJ4AHLgVZcmNYlO57JegAoKsAEyV5V" +
      "IazBrosuAuYCMAEUlR5mviknkwa2twI6MT+IAC+ALqxDGpaOiD+NBDYAOaShsYEVHDYJAiScOQYONxZkmCIMNEqIMS4TNiYfmCS1vrSNJLkSvHtmPR4UohQxAlMUJpIaH" +
      "YOYWkZWblM1hBs2FBu3EUlxGVzmHT4oPncvXJwZqnc05lNWxCGlQcEvVDkrds5STaTKYazcOJMJAsCDjACsAAYkilwrodn1trt9tVUWxJNkXNgYJFMhpuOYRJ4ABJ+c7j" +
      "K5GExoh4oxxovYHN4fKruEBwX7/DYQwg7GH4QkIBCzdJWJr2elSBStP43E5oe5MKTnFjoS7MR7fIxwIn0Jj1BCNcFJPUsth85xcJEgfKK7DKwqYGDYE3SLU6vDItK9SbG" +
      "uoNNJC1bcW2wQwQ+Uut286y9MEa31062Bw0h01hy2hfUgaP2uIjECaLIkazeNlYvbNI6lSTYOBseYVPrQABKmAARmMQGWK8drABlWkqu6SBDEbL/XUY1p1w7UY6nYXQ8b" +
      "ihC582y0Dw7gdSSeJ7dJgAZm4UgGTAALIclExYdxWkLqFAAHJEsoTKYzJhKAgbJKCQECMxkOQFGWANGVxAwGRxPo9C7Yo5xg9I1QuAgACZ4U8WFSHhABOYIcIpeE8HhSj" +
      "qIAOmo+EAC1JHnXD8MIkiyIpTwqJo+F6Oo5iEilYtY3dT16FiWIgA";
  }

  static noSlashInEncodedDefinition2() {
    return "line-chart/2/EQUQLgxg9AqgKgYWAGgN7APYAdgC5MBuApgE4A2AhjsplqRQHYAme62ewJRAZisAxQC2RDmACWw4AF8aRAB5YuAZyViMDVrVESiA" +
      "JUYBzETWz1mm9vi68aAyfkHSaTAK4kK49RwAKARgAifEpgRDi4ALS+UjIA2ujyikQqahq4bGGcPHx2IvjikjLAAEYuEADWRGAAghCeqenawgBCpRVgfK7u" +
      "dT5wvgASTsBKGCTVtSkWGcOjfAnKql5pWlZZtkK5wPkihUxiXOOLwBRKEETMYgwG0lIAushgJC5EzkRkYBQoMcAQGC4M7XcvhAABaMBivbLrJRYCinPhiJ" +
      "S6DBFDAAl5vD7IBguMhkLE4vHY3FAA==";
  }

  static noSlashInEncodedDefinition3() {
    return "3/N4IgbglgzgrghgGwgLzgFwgewHYgFwhLYCmAtAMYAWcATmiADQgYC2xyOx+IAomuQHoAqgBUAwoxAAzCAjTEaUfAG1QaAJ4AHLgVZcmNYlO57Je" +
      "gAoKsAEyV5VIazBrosuAuYCMAETNadhOjEUPRMIcSa+KSeAL4AuvFhmkhodg4a2iYQbJLW2cTYUG5ZOUwA5i7YMAi0EBrc5iKeABKSUJh0+KCGxrr5uRCG" +
      "5Bg43HBQ5AV52GUgMUxILHX4VQgIiSBs487BXSDQALLVGPhoNDDEYRAzCAHWxHJwkizHECog5Jgw2PQJTJrXEjWbz5QpuNIfajYEgISTYOBsKCaOCTSTQA" +
      "BKmAARphfv9AcRrABlDr0Aj3R6SW5lKYraoIJiUCBlShIFlk1brIA";
  }
}
