#!/bin/bash -eu

# Force this to the working directory
cd "$(dirname "$0")"

mkdir -p ../data

gzcat wikiticker-2015-09-12.gz \
  | jq -c '
    {
      time: .timestamp,
      channel,
      cityName,
      comment,
      countryIsoCode,
      countryName,
      isMinor,
      isNew,
      isRobot,
      isUnpatrolled,
      metroCode,
      namespace,
      page,
      regionIsoCode,
      regionName,
      user,
      delta,
      added: [.delta, 0] | max,
      deleted: [-.delta, 0] | max
    }' \
  > ../data/wikiticker-2015-09-12-large.json

perl -ne'print if $. % 10 == 0' ../data/wikiticker-2015-09-12-large.json > ../data/wikiticker-2015-09-12-sampled.json
