// Docs: https://github.com/sasstools/sass-lint/tree/develop/docs/rules
module.exports = {
  "attribute-quotes": 1,
  "bem-depth": 0,
  "border-zero": [1, {"convention": "0"}],
  "brace-style": [1, {"allow-single-line": true}],
  "class-name-format": [1, { "allow-leading-underscore": false, "convention": "hyphenatedlowercase" }],
  "clean-import-paths": [1, {"filename-extension": false, "leading-underscore": false}],
  "empty-args": 0,
  "empty-line-between-blocks": [1, {"ignore-single-line-rulesets": true}],
  "extends-before-declarations": 1,
  "extends-before-mixins": 1,
  "final-newline": [1, {"include": true}],
  "force-attribute-nesting": 0,
  "force-element-nesting": 0,
  "force-pseudo-nesting": 0,
  "function-name-format": [1, {"allow-leading-underscore": true, "convention": "hyphenatedlowercase"}],
  "hex-length": [0, {"style": "short"}],
  "hex-notation": [1, {"style": "lowercase"}],
  "id-name-format": [1, { "allow-leading-underscore": false, "convention": "hyphenatedlowercase" }],
  "indentation": [1, {"size": 2}],
  "leading-zero": [0, {"include": false}],
  "mixin-name-format": [1, {"allow-leading-underscore": true, "convention": "hyphenatedlowercase"}],
  "mixins-before-declarations": 1,
  "nesting-depth": [1, {"max-depth": 6}],
  "no-attribute-selectors": 0,
  "no-color-keywords": 1,
  "no-color-literals": 0,
  "no-combinators": 0,
  "no-css-comments": 0,
  "no-debug": 1,
  "no-disallowed-properties": 0,
  "no-duplicate-properties": 0,
  "no-empty-rulesets": 0,
  "no-extends": 0,
  "no-ids": 1,
  "no-important": 1,
  "no-invalid-hex": 1,
  "no-mergeable-selectors": 0, // This falls over on animation definitions
  "no-misspelled-properties": [1, {"extra-properties": []}],
  "no-qualifying-elements": [0, { "allow-element-with-attribute": false, "allow-element-with-class": false, "allow-element-with-id": false }],
  "no-trailing-whitespace": 1,
  "no-trailing-zero": 0,
  "no-transition-all": false,
  "no-universal-selectors": 0,
  "no-url-protocols": 1,
  "no-vendor-prefixes": [1, {"additional-identifiers": [], "excluded-identifiers": []}],
  "no-warn": 1,
  "one-declaration-per-line": 1,
  "placeholder-in-extend": 1,
  "placeholder-name-format": [1, {"allow-leading-underscore": true, "convention": "hyphenatedlowercase"}],
  "property-sort-order": 0,
  "property-units": 0,
  "pseudo-element": 1,
  "quotes": [1, {"style": "single"}],
  "shorthand-values": [0, {"allowed-shorthands": [1, 2, 3]}],
  "single-line-per-selector": 0,
  "space-after-bang": [1, {"include": false}],
  "space-after-colon": [1, {"include": true}],
  "space-after-comma": 1,
  "space-around-operator": 0,
  "space-before-bang": [1, {"include": true}],
  "space-before-brace": [1, {"include": true}],
  "space-before-colon": 1,
  "space-between-parens": [1, {"include": false}],
  "trailing-semicolon": 1,
  "url-quotes": 1,
  "variable-for-property": [0, {"properties": []}],
  "variable-name-format": [1, {"allow-leading-underscore": true, "convention": "hyphenatedlowercase"}],
  "zero-unit": 1
};
