#!/bin/bash -e

# This script is used to quickly 'npm install plywood@super-latest' without having to publish plywood.
# Assumes /pivot and /plywood are next to each other

cp -r ../plywood/package ./node_modules/plywood
cp -r ../plywood/build ./node_modules/plywood
cp -r ../plywood/src ./node_modules/plywood
cp -r ../plywood/test ./node_modules/plywood
