# The port on which the Turnilo server will listen on
port: 9090

clusters:
  - name: druid
    type: druid
    host: the.druid.host:8082 # This happens to be my Docker machine

    requestDecorator:
      path: './druid-request-decorator.js'
      options:
        base: Pancakes
        extras:
          - Blueberries

