name: CI

on:
  workflow_dispatch: ~
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: npm run lint

  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14', '16']

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build
      - run: npm run test

  e2e-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14', '16']

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build
      - run: npm run e2e

  required-checks:
    needs: [lint, unit-test, e2e-test]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  deploy:
    needs: required-checks
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  reports:
    needs: required-checks
    uses: ./.github/workflows/reports.yml
    secrets: inherit

  all-checks:
    needs: [required-checks, deploy, reports]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
