name: Lighthouse Report

on:
  workflow_call: ~
  workflow_dispatch: ~

jobs:
  lighthouse-report:
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    # add permission to comment PR created by dependantbot
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: npm run build
      - uses: treosh/lighthouse-ci-action@v9
        with:
          uploadArtifacts: true
          temporaryPublicStorage: true
