name: Lighthouse Report

on:
  workflow_call: ~
  workflow_dispatch: ~

jobs:
  lighthouse-report:
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    # add permission to comment PR created by dependantbot
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: npm run build
      - uses: treosh/lighthouse-ci-action@v9
        id: lighthouse
        with:
          uploadArtifacts: true
          temporaryPublicStorage: true
      - uses: actions/github-script@v6
        env:
        with:
          script: |
            const lighthouse_links = ${{ steps.lighthouse.outputs.links }}
            const lighthouse_link = Object.values(lighthouse_links)[0]
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':stopwatch: Lighthouse [report](' + lighthouse_link + ')' 
            })
