name: Undeploy Branch

on:
  workflow_dispatch: ~
  pull_request:
    types: [closed]

jobs:
  undeploy:
    runs-on: ubuntu-latest

    # disable for branches from forks
    if: github.repository == 'allegro/turnilo'

    env:
      IMAGE_NAME: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/turnilo
      TAG_NAME: ${{ github.head_ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GCloud
        uses: ./.github/actions/gcloud
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Undeploy app
        run: |
          gcloud run services delete turnilo-${TAG_NAME//[^a-z0-9]/-} \
            --region europe-west1 \
            --quiet

      - name: Delete Docker image
        run: |
          gcloud container images delete $IMAGE_NAME:${TAG_NAME//[^a-z0-9]/-} --quiet
